### ISSUE TITLE
response None? 

### ISSUE THREAD

**Issue by arnoldliaoILMN** [alexpreynolds/soda#1]
I got a None response from this command

C:\Users\aliao\Downloads\soda-master\soda-master>python soda.py -r input.bed -b
"hg19" -s "578580129_wPAOj1hiZ8CLt5Iku8bqiCPtVFWk" -o "soda_out" -k "C:\Program
Files\ImageMagick-7.0.4-Q16" -n "C:\Program Files\ImageMagick-7.0.4-Q16" -v
Debug: Midpoint annotation disabled
Debug: Interval annotation disabled
Debug: Annotation RGBA color string set to [rgba(255, 0, 0, 0.333)]
Debug: Annotation font point size string set to [5]
Debug: Annotation font family set to [Helvetica]
Debug: Created final results dir [soda_out]
Debug: Regions file exists [input.bed]
Debug: Gallery resources directory exists [C:\Users\aliao\Downloads\soda-master\
soda-master\Gallery]
Debug: Github Octicons resources directory exists [C:\Users\aliao\Downloads\soda
-master\soda-master\octicons]
Debug: Convert binary path exists [C:\Program Files\ImageMagick-7.0.4-Q16]
Debug: Identify binary path exists [C:\Program Files\ImageMagick-7.0.4-Q16]
Debug: Created temp results dir [c:\users\aliao\appdata\local\temp\tmpi59zu7]
Debug: Created temp regions results dir [c:\users\aliao\appdata\local\temp\tmpi5
9zu7\regions]
Debug: Created temp PDF results dir [c:\users\aliao\appdata\local\temp\tmpi59zu7
\pdfs]
Debug: Created temp PNG results dir [c:\users\aliao\appdata\local\temp\tmpi59zu7
\images]
Debug: Created temp thumbnails results dir [c:\users\aliao\appdata\local\temp\tm
pi59zu7\images\thumbnails]
Debug: Copied [input.bed] to [c:\users\aliao\appdata\local\temp\tmpi59zu7\region
s\input.bed]
Debug: Annotated regions file written to [c:\users\aliao\appdata\local\temp\tmpi
59zu7\regions\input.bed.annotated]
Debug: Browser URL set to [https://genome.ucsc.edu]
Debug: Browser username set to [None]
Debug: Browser password set to [None]
Debug: Browser build ID set to [hg19]
Debug: Browser session ID set to [578580129_wPAOj1hiZ8CLt5Iku8bqiCPtVFWk]
Debug: Browser dump URL set to [https://genome.ucsc.edu/cgi-bin/cartDump]
Debug: Browser PDF URL set to [https://genome.ucsc.edu/cgi-bin/hgTracks?hgsid=57
8580129_wPAOj1hiZ8CLt5Iku8bqiCPtVFWk&hgt.psOutput=on&db=hg19]
Debug: Submitting POST body [{u'hgsid': '578580129_wPAOj1hiZ8CLt5Iku8bqiCPtVFWk'
, u'cartDump.varName': u'position', u'cartDump.newValue': 'chr2:117174313-117174
412', u'hgt.psOutput': u'on', u'submit': u'submit'}] to request
**Debug: Cart dump textSize and hgt.labelWidth are: [None] and [None]**
Traceback (most recent call last):
  File "soda.py", line 858, in <module>
    main()
  File "soda.py", line 849, in main
    s.generate_pdfs_from_annotated_regions(options.verbose)
  File "soda.py", line 423, in generate_pdfs_from_annotated_regions
    this.generate_pdf_from_annotated_region(region_obj, region_id, debug)
  File "soda.py", line 462, in generate_pdf_from_annotated_region
    this.setup_track_label_column_width(int(browser_cartdump_textSize), int(brow
ser_cartdump_hgt_labelWidth), debug)
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by alexpreynolds** [comment]
Hi,

Can you please export your UCSC browser session to a file that I can
download and load locally, to try to troubleshoot why those variables are
not set?

Thanks,
Alex

**Comment by alexpreynolds** [comment]
(You can also export the session to a text file and post in this thread, if you prefer.)

**Comment by alexpreynolds** [comment]
I applied some patches to bring this in line with an internal version I keep of soda.py and got some figures, e.g.:

![plot_000000_chr2_117174313_117174412](https://cloud.githubusercontent.com/assets/33584/22848923/eda884d8-efac-11e6-86e0-3a8facd53ab3.png)

Please run this script again and update the ticket if you run into further problems.
