### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by gk7279** [alexpreynolds/soda#2]
Hi Alex,

I installed all dependencies and when I try to see the help menu of soda, I get this error

`File "./soda.py", line 469
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax`

**Comment by alexpreynolds** [comment]
Hm. Looks like some commit diff text worked its way into the main script. I removed it in commit f004ded so please feel free to pull the latest changes and try it again.

**Comment by gk7279** [comment]
Asked for requests-kerberos, pdfminer.six in addition to the requirements that you specified. Works great. Thanks.

**Comment by alexpreynolds** [comment]
Great! Thanks for the bug report.
