### ISSUE TITLE
Suggestion to have genomic region in index page

### ISSUE THREAD

**Issue by gopi1616** [alexpreynolds/soda#3]
Hi Alex, this is not issue and just a suggestion.  First of all this a great tool, I really appreciate your work. I just have a suggestion and I wasn't sure how to communicate with you so I am adding it in issues.

It would be great if we have something like a list of the genomic region from the given bed and an option to view the corresponding UCSC image while hovering on the region_name in the home page. This way user can look into region they are interested immediately instead of scrolling through the slides one by one to reach the one they want. Slide also looks great but having this option in addition will really help. Thanks again for making this open source tool.

**Comment by alexpreynolds** [comment]
Thanks, I'll take a look when I have bandwidth. Sounds reasonable.

**Comment by gopi1616** [comment]
Great. Thanks.

**Comment by alexpreynolds** [comment]
This tool has been updated to add some UI improvements. It has been repackaged with support for Python 3 and dependencies, and it is now available via PyPi:

```
$ pip install soda-gallery
```

Ref: https://pypi.org/project/soda-gallery/
