### ISSUE TITLE
session ID

### ISSUE THREAD

**Issue by zhengrongbin** [alexpreynolds/soda#4]
Hi Alex - I'm new in this tool and found that this is a very useful function. 
I met a problem, maybe it's easily but I don't know. I wonder how to get the UCSC session id which is required by -s. I have created a UCSC session named rongbin_lncRNA, shouldn't I give -s "rongbin_lncRNA"? But it shows the error "Error: No or more than one PDF available for this region". I am sure the regions in the BED file is correct. I need to use my session is because I want to do screen shot on my own track.  Thanks in advance.

**Comment by zhengrongbin** [comment]
Hi Alex - Do you mean this one https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr1%3A11102837%2D11267747&hgsid=685769457_TZq7UNM3k16YTeJmEL073YPKTZt1

Best!

Rongbin Zheng

**Comment by zhengrongbin** [comment]
Alex, I find the session id, the id is just the characters after "hgsid" in this link. thanks for your help.

**Comment by alexpreynolds** [comment]
Yes, the session ID to use is "685769457_TZq7UNM3k16YTeJmEL073YPKTZt1" (no
quotes).

Regards,
Alex
