### ISSUE TITLE
Incompatibility with Python 3 resolved using Python 2.7

### ISSUE THREAD

**Issue by Suhoja** [alexpreynolds/soda#5]
Hi,

I did not manage to get this script to work with Python 3, so just as a heads up for future users running into issues:
**Be sure to install this using Python 2.7** 

To be on the safe side I also installed all pre Aug 2017 versions of the dependencies and got it to run flawlessly.

**Comment by alexpreynolds** [comment]
This tool has been repackaged with support for Python 3 and dependencies, and it is now available via PyPi:

```
$ pip install soda-gallery
```

Ref: https://pypi.org/project/soda-gallery/
