### ISSUE TITLE
NameError: name 'ucsc_pdf_bbox_parser' is not defined

### ISSUE THREAD

**Issue by dominik-handler** [alexpreynolds/soda#6]
Hi,

I wanted to try soda, but I always run into the same error:
```
Traceback (most recent call last):
  File "/usr/local/bin/soda", line 8, in <module>
    sys.exit(main())
  File "/users/handler/.local/lib/python3.6/site-packages/soda/soda.py", line 905, in main
    s.generate_pdfs_from_annotated_regions(options.verbose)
  File "/users/handler/.local/lib/python3.6/site-packages/soda/soda.py", line 423, in generate_pdfs_from_annotated_regions
    this.generate_pdf_from_annotated_region(region_obj, region_id, debug)
  File "/users/handler/.local/lib/python3.6/site-packages/soda/soda.py", line 562, in generate_pdf_from_annotated_region
    ucsc_pdf_bbox_parser.set_fn(browser_pdf_local_fn)
NameError: name 'ucsc_pdf_bbox_parser' is not defined
```

I tried to install soda via pip and via conda in an environment. Do you have any idea what I can do to fix this problem?

Thank you and all the best,
Dominik

**Comment by alexpreynolds** [comment]
I'm not sure what's wrong. I'll try to get up a test environment to see if I can run into the same issue.

In the meantime, however, perhaps you can try to copy this file to `/users/handler/.local/lib/python3.6/site-packages/soda`:

https://raw.githubusercontent.com/alexpreynolds/soda/master/soda/ucsc_pdf_bbox_parser.py

So long as it is in the same folder as the main `soda.py` script, that should make its functionality available.

**Comment by dominik-handler** [comment]
Thank you for you quick reply!

![image](https://user-images.githubusercontent.com/12491961/142271490-02c10a26-c5a7-448b-bb10-0ded85e34f30.png)
I checked and the file is present. I also tried to install it again in a fresh virtualenv and got the same error message. Again the file is present at the intended location.

**Comment by alexpreynolds** [comment]
Thanks for trying it out. I'll try to investigate soon.

**Comment by alexpreynolds** [comment]
Sorry for the delay. I set up a test environment and I was not able to reproduce your error report.

I am using the following versions of macOS and Anaconda:

```
$ sw_vers
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
$ conda --version
conda 4.10.1
```

Here is the command I used to set up and activate the test environment (Python 3.10):

```
$ conda create -n soda-test python=3.10
$ conda activate soda-test
```

Here is the tab-delimited BED file I used for making a test gallery:

```
$ cat /tmp/test.bed
chr11	5275000	5300000
```

Here is the command I issued:

```
$ soda -r "/tmp/test.bed" -b "hg38" -s "1224498593_kkCZ3mODSyvsLuEDfcJVSGvquxqY" -o "/tmp/gallery"
```

The session ID `1224498593_kkCZ3mODSyvsLuEDfcJVSGvquxqY` is from the main production UCSC Genome Browser, pointing to an hg38-based session. The test interval should look like this on the live site: http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr11%3A5275000%2D5300000&hgsid=1224498593_kkCZ3mODSyvsLuEDfcJVSGvquxqY

To open the gallery:

```
$ open "/tmp/gallery/index.html"
```

This looks something like the following:

<img width="1047" alt="Screen Shot 2021-11-26 at 5 23 18 PM" src="https://user-images.githubusercontent.com/33584/143663909-3781de73-d152-4ff3-a94a-43e1731c925c.png">

Not sure what's up. If you can pass along some more details about your setup that I can try to reproduce on my end, I'll reopen this issue and try to troubleshoot some more. Thanks!

**Comment by dominik-handler** [comment]
Hi, 

thank you for all the tips. I don't know why but now everything is working properly. Not only the version I install according to your example above, but also the one that used not to work. 

I hope everything stays like this. Soda is really awesome!

Thank you for your help. In case I run again into the problem and find something relevant I will write you again.
